### ISSUE TITLE
Investigate backward compatibility support in ConfluentSchemaRegistryClient

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-schema-registry#10]
Find out what version of the schema registry that includes the breaking changes to the REST APIs.

**Comment by frombrest** [comment]
I suppose that ConfluentSchemaRegistryClient:153
`	@Override
	public String fetch(int id) {
		String path = String.format("/schemas/%d", id);
		HttpHeaders headers = new HttpHeaders();
`
Should be
`
		String path = String.format("/schemas/ids/%d", id);
`

**Comment by sabbyanandan** [comment]
Thanks for fixing this, @frombrest! Addressed in https://github.com/spring-cloud/spring-cloud-schema-registry/commit/0cdff772bf62c33c8b578b143f5184666842ded0.
