### ISSUE TITLE
spring-cloud-schema-registry-client project imports tomcat dependencies

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-cloud/spring-cloud-schema-registry#23]
Trying to add spring-cloud-schema-registry client to a reactive project, I realized that the module **spring-cloud-schema-client** brings transitively the **spring-boot-starter-tomcat** dependency through **spring-boot-starter-web** .

Shouldn't it import **spring-web** instead? 

I tried to exlude it and seems to work perfectly: 

```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-schema-registry-client</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
```

As far as I am concerned, the client should be agnostic of the relying server of the application

**Comment by tzolov** [comment]
Hi @JordiMartinezVicent , 
thanks for reporting this misconfiguration!
