### ISSUE TITLE
Is 2.2.1.RELEASE of spring cloud stream schema is latest and works with Spring boot 2.2.5?

### ISSUE THREAD

**Issue by santhoshpt** [spring-cloud/spring-cloud-schema-registry#31]
Is the 2.2.1.RELEASE of spring cloud stream schema latest?  Can we use it with spring boot 2.2.5 and Hoxton.SR3, Horsham.SR3 depencies?

There are other latest version available in the spring milestones ( https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream-schema?repo=springio-milestone) and why these latest versions are not available as part of central (https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream-schema) in MVN respository?

**Comment by sabbyanandan** [comment]
@santhoshpt: The `spring-cloud-stream-schema` module has been moved to a standalone project, and it is not chained under Spring Cloud Stream anymore. More details [here](https://spring.io/blog/2019/11/25/announcing-the-release-of-spring-cloud-stream-horsham-3-0-0-release). 

Please look for correct artifact-id in maven.
