### ISSUE TITLE
spring-cloud-stream-schema module is no longer used but it's mentioned in the doc

### ISSUE THREAD

**Issue by xiongjiaji** [spring-cloud/spring-cloud-schema-registry#34]
In spring-cloud-schema-registry.adoc, we can see the statements like:

> Spring Cloud Stream provides support for schema-based message converters through its spring-cloud-stream-schema module.

> The spring-cloud-stream-schema module contains two types of message converters that can be used for Apache Avro serialization

But spring-cloud-stream-schema is the old module name, we need to update the doc to the right module name `spring-cloud-schema-registry-client`.

The PR of this fix: https://github.com/spring-cloud/spring-cloud-schema-registry/pull/35

Please review. Thanks!

**Comment by kyxiong-sh** [comment]
@tzolov Could you please help review the PR? Thanks!
