### ISSUE TITLE
Is This Project Deprecated?

### ISSUE THREAD

**Issue by neilchaudhuri** [spring-cloud/spring-cloud-schema-registry#56]
Just want to ask since it sure looks that way. And if so, I would love some suggestions from the community on alternatives outside of Confluent's Schema Registry, which is backed by Kafka and therefore isn't an option right now. Thanks

**Comment by kabennett** [comment]
To add to this, vulnerability scans of spring-cloud-schema-registry-server report h2 dependency vulnerabilities. So, what is the status of this project, especially in light of the fact that the latest version has vulnerabilities that could be remediated easily I would think?

**Comment by bitfist** [comment]
Seems like the project is now part of the spring-cloud-stream project, see https://github.com/spring-cloud/spring-cloud-stream/tree/main/schema-registry

**Comment by sobychacko** [comment]
Yes, you are right. This project is moved as part of the core Spring Cloud Stream. Here is a blog we published last year on this matter: https://spring.io/blog/2022/11/10/updates-on-spring-cloud-stream-4-0-0-schema-registry-support
